# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNNxlauthExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNNxlauthExample
  pod 'AppAuth', :git => 'https://github.com/nexlife/AppAuth-iOS.git'

  
end

